ignore group membership
EMBL-EBI-TSI/tesk-api pull request #12
Opened 2020-10-01 10:15 UTC by navisatebi

Created a new branch, to keep commits clean. Formatting and get Task changed as per requirements.
IT added to cover the new set of requirements.

2020-10-07 11:37 UTC, aniewielska requested changes

2020-10-07 11:37 UTC, aniewielska commented on src/main/java/uk/ac/ebi/tsc/tesk/util/component/KubernetesClientWrapper.java
> +            labelSelector += "," + new StringJoiner("=").add(LABEL_USERID_KEY).add(user.getUsername()).toString();
Could you please follow the formatting used in the code (I asked about it before)?

2020-10-07 11:37 UTC, aniewielska commented on src/main/resources/application.properties
> +spring.profiles.active=auth
Could you please not change the default to authenticated mode?

2020-10-07 11:37 UTC, aniewielska commented on src/main/java/uk/ac/ebi/tsc/tesk/service/TesService.java
> +    @PreAuthorize("(authentication.authenticated AND @authorisationProperties.isIgnoreGroupMembership()) OR (hasRole(@authorisationProperties.baseGroupFull) AND" +
Is `authentication.authenticated` really necessary? (I believe it is not).

2020-10-07 11:37 UTC, aniewielska commented on src/main/java/uk/ac/ebi/tsc/tesk/service/TesService.java
>              " OR (#user.teskAdmin)" +
This condition can be simplified: isOwner and either ignoreMembership or belong to a group.

2020-10-07 11:37 UTC, aniewielska commented on src/integration-test/java/uk/ac/ebi/tsc/tesk/AuthIT.java
> +                "spring.profiles.active=auth","tesk.api.authorisation.ignoreGroupMembership=false"})
Why is this additional property needed here? It should work by default.

2020-10-07 11:37 UTC, aniewielska commented on src/integration-test/java/uk/ac/ebi/tsc/tesk/NoAuthIT.java
> +                "spring.profiles.active=noauth","tesk.api.authorisation.ignoreGroupMembership=false"})
Same as above.

2020-10-07 11:37 UTC, aniewielska commented on src/main/java/uk/ac/ebi/tsc/tesk/service/TesService.java
>              "(#user.member OR #user.teskAdmin) AND" +
Is `authentication.authenticated` necessary? What happens, if you remove it?

2020-10-07 11:37 UTC, aniewielska commented on src/main/java/uk/ac/ebi/tsc/tesk/service/TesService.java
> +    @PostAuthorize("(authentication.authenticated AND @authorisationProperties.isIgnoreGroupMembership() AND #user.username == returnObject.logs[0].metadata['USER_ID']) OR (#user.username == returnOb
This condition can be simplified to: isOwner and (is a groupMember or ignoreMembership)

2020-10-07 11:37 UTC, aniewielska commented on src/main/java/uk/ac/ebi/tsc/tesk/util/component/KubernetesClientWrapper.java
> +        }
Here formatting does not follow the standards used in the code (space after if) and I believe this code does not work for a user, who belongs to any group: the tasks outside of any groups, but still belonging to the user will not show up. The idea is that the label selector for `ignoreMembership` should not include checking groups at all.

2020-10-07 11:37 UTC, aniewielska commented on src/main/resources/application.properties
> +spring.profiles.active=auth
Please do not set authenticated mode by default.

2020-10-07 11:37 UTC, aniewielska commented on src/integration-test/java/uk/ac/ebi/tsc/tesk/AuthIgnoreGroupMembershipIT.java
> +
I think we can show the point of membership not interfering with ignoreMembership and still not copy all the tests from the previous test suite. Are they really necessary?

2020-10-07 11:37 UTC, aniewielska commented on src/integration-test/java/uk/ac/ebi/tsc/tesk/AuthIgnoreGroupMembershipIT.java
> +
Doesn't the non-member belong here to the same group as member (in fact being a member)?

2020-11-04 13:57 UTC, closed without merging

2020-11-04 13:57 UTC, navisatebi commented
More development in another branch